# Generated by Django 3.2 on 2022-04-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("location", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="district",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="district",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="location",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="location",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="province",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="province",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
