# Generated by Django 3.2 on 2022-02-23 07:18

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_distinct'),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(allow_unicode='True')),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='distinct',
        ),
        migrations.AddField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode='True', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(default=datetime.datetime(2022, 2, 23, 7, 18, 52, 366712, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='location.province'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='province',
            name='slug',
            field=models.SlugField(allow_unicode='True', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Distinct',
        ),
        migrations.AddField(
            model_name='district',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='districts', to='location.city'),
        ),
        migrations.AddField(
            model_name='location',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='location.district'),
        ),
    ]
