# Generated by Django 3.2 on 2022-04-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_auto_20220430_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
