# Generated by Django 3.2 on 2022-05-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_auto_20220430_2352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(allow_unicode='True', blank=True, unique=True),
        ),
    ]
