# Generated by Django 3.2 on 2022-04-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Enter a valid Email address",
                max_length=254,
                verbose_name="email address",
            ),
        ),
    ]
