# Generated by Django 3.2 on 2022-06-07 02:34

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("financial", "0002_auto_20220606_0301"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="gateway",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payments",
                to="financial.gateway",
                verbose_name="gateway",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="invoice_number",
            field=models.UUIDField(
                default=uuid.UUID("3f528369-3002-4dfb-8749-6a84eb210d87"),
                verbose_name="invoice number",
            ),
        ),
    ]
