# Generated by Django 3.2 on 2022-04-11 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('category', '0001_initial'),
        ('account', '0002_auto_20220223_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('price', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='category.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='location.location')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='account.profile')),
            ],
            options={
                'verbose_name': 'Advertisement',
                'verbose_name_plural': 'Advertisements',
            },
        ),
    ]
