# Generated by Django 3.2 on 2022-04-30 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("advertisement", "0003_advattrvalue_attribute"),
    ]

    operations = [
        migrations.AddField(
            model_name="advertisement",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="advertisement",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="image",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="modified_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
