# Generated by Django 3.2 on 2022-04-30 23:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('advertisement', '0004_auto_20220430_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True,
                                       default=datetime.datetime(2022, 4, 30, 23, 51, 37, 904633, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
