# Generated by Django 3.2 on 2022-05-01 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('advertisement', '0008_advertisementimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisementimage',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
