# Generated by Django 3.2 on 2022-04-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0002_auto_20220430_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
