# Generated by Django 3.2 on 2022-05-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('category', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, null=True),
        ),
    ]
